# ~/.config/starship.toml

# Use custom format
# Move the directory to the second line
format = """
[┌─](cyan)\
[\\(](cyan)\
$username\
[\\)](cyan)\
[─](cyan)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[\\[](cyan)\
$directory\
[\\]](cyan)
[└─](cyan)[\\$ ](bold white)
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

# Set 'foo' as custom color palette
palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'

[username]
show_always = true
style_user = 'bold white'
style_root = 'bold red'
format = '[$user]($style)'

[directory]
format = '[$path]($style)'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)'
style = 'bold white'
read_only_style = 'bold red'
truncate_to_repo = false

[git_branch]
format = '[\(](cyan)[$branch(:$remote_branch)]($style)'

[git_commit]
format = '[\($hash$tag\)]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))[\)─](cyan)'
